<?php
$content = $content ?? "<p>Page temporarily unavailable</p>";
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=yes, initial-scale=1.0, maximum-scale=5.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Custom Php MVC</title>

    <link rel="stylesheet" href="<?= SITE ?>/css/main.css">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Pattaya&family=Poppins&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <div class="container flex">
            <a href="<?= SITE ?>">Home</a>
            <nav class="navbar">
                <a href="<?= SITE ?>/Articles">Articles</a>
                <a href="<?= SITE ?>/About">About</a>
                <a href="<?= SITE ?>/User/login">Login</a>
            </nav>
        </div>
    </header>
    <main class="container">
        <?= $content ?>
    </main>
    <footer>
        <div class="container flex">
            <p>Made By Boniface Yohann</p>
            <a href="https://github.com/Sigmanificient">
                <img src="" alt="">
            </a>
        </div>
    </footer>
</body>
</html>